### PR TITLE
Update runtime to 24.08

### PR DESCRIPTION
**Pull request by zhsj**
Closes: #152

### CODE REVIEW

**Comment by AsciiWolf** [comment]
@SystemlessDev Any chance you could test this?

**Comment by zhsj** [comment]
image

It just works.

**Comment by AsciiWolf** [comment]
Did you try new installation (clean Flatpak app directory)?

**Comment by zhsj** [comment]
image
image

Works for fresh installation.

**Comment by AsciiWolf** [comment]
Thanks!

**Pull request merged**
