### PR TITLE
Bundle gnome keyring to workaround kde's lack of secrets portal support.

### PR DESCRIPTION
**Pull request by vchernin**
Needs testing, see https://github.com/flathub/com.mojang.Minecraft/issues/116

### CODE REVIEW

**Comment by AsciiWolf** [comment]
It probably also needs [gcr/gck](https://gitlab.gnome.org/GNOME/gcr).

**Review by AsciiWolf — CHANGES_REQUESTED** [review]
It sadly does not seem to help, see [this](https://github.com/flathub/com.mojang.Minecraft/issues/116#issuecomment-1085983929) comment.

**Comment by vchernin** [comment]
too bad :( I will close for now then

**Comment by hellcp** [comment]
It's not particularly surprising it didn't work, the example brought up in the thread also included [this script](https://github.com/flathub/org.gnome.Evolution/blob/6b363e4f1b330a4d816eedb6af961141f72006df/org.gnome.Evolution.json#L292-L308), which shows how to start gnome-keyring-daemon so it is launched inside flatpak, before starting the application itself.

**Pull request closed without merging**
