### PR TITLE
Replace PolyMC recommendation with Prism

### PR DESCRIPTION
**Pull request by SystemlessDev**
See this article for more info: https://www.gamingonlinux.com/2022/10/if-you-use-polymc-for-minecraft-you-should-switch-away-now/

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Thanks!

By the way, I would like to ask you again: Any chance you would be interested in having push rights to this repository (and becoming a Minecraft Flatpak co-maintainer)? I am having quite a hard time being the only active maintainer and would highly appreciate any help. :-) If you are interested, please let me know. Thanks!

**Comment by SystemlessDev** [comment]
I'll gladly help you out yeah. Feel free to add me on Discord if you want a proper communication medium to talk on `Systemless#0001`

**Comment by AsciiWolf** [comment]
Cool! Thanks a lot! I may add you later, but I am mostly offline on Discord. But feel free to contact me via e-mail if needed. :-)

@bilelmoussaoui @nedrichards Please, add @SystemlessDev push rights to the _com.mojang.Minecraft_ repository. Thanks!

**Comment by barthalion** [comment]
I've sent the invite.

**Pull request merged**
