### PR TITLE
Update Minecraft.tar.gz size/hash

### PR DESCRIPTION
**Pull request by camdenorrb**

### CODE REVIEW

**Comment by camdenorrb** [comment]
Thanks for the hand ^-^

**Comment by nedrichards** [comment]
Runs in test

**Comment by cdplayer** [comment]
Still failing: 
com.mojang.Minecraft permissions:
    ipc    network    pulseaudio    x11    dri    tags [1]

    [1] proprietary


        ID                            Arch             Branch          Remote           Download
 1. [✗] com.mojang.Minecraft          aarch64          stable          flathub          67.5 MB / 129.0 MB

Error: Wrong size for extra data https://launcher.mojang.com/download/Minecraft.tar.gz
error: Failed to install com.mojang.Minecraft: Wrong size for extra data https://launcher.mojang.com/download/Minecraft.tar.gz

**Comment by AsciiWolf** [comment]
Hmm, it's probably some really old build, Minecraft Flatpak isn't even available (it was previously, by mistake) for aarch64.

**Pull request merged**
