### PR TITLE
Add translations to appdata

### PR DESCRIPTION
**Pull request by LeandroStanger**
These translations are from the appdata Minecraft Flatpak from Endless https://github.com/endlessm/flatpak-minecraft/blob/master/com.mojang.Minecraft.appdata.xml

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Thanks. I am not sure if not including the `NOTE: This wrapper is not verified by, affiliated with, or supported by Mojang or Microsoft.` part in other languages is ok. I would include it, at least in the original English version. Also, AppStream validation seems to be failing:
```
• style-invalid         : <p> cannot contain a hyperlink [Join people all over the world playing Minecraft, one of the most popular videogames around! Your own imagination is the limit in this fun game where you get to build the world around you. Play with friends, or alone, as you adventure, gather, build, and battle in an incredible land of your very own. For the best experience, we recommend you create an account and purchase online at https://minecraft.net/en-us/store/ before installing this app. ** Requires internet.]
```

However, just during `validate`, `validate-relax` seems to be ok with this.

**Comment by LeandroStanger** [comment]
bot, build com.mojang.Minecraft

**Comment by AsciiWolf** [comment]
Thanks for the update. It would probably be also good to add this (just like it is in the original AppData from endlessm):
```
  <metadata>
    <value key="GnomeSoftware::popular-background">https://d3lapyynmdp1i9.cloudfront.net/thumbnails/com.mojang.Minecraft/com.mojang.minecraft-thumb.jpg</value>
  </metadata>
```
It is primarily for Endless OS, but should not do any harm having it here.

**Comment by LeandroStanger** [comment]
bot, build com.mojang.Minecraft

**Comment by AsciiWolf** [comment]
@Kekun Is this ok to merge?

**Comment by AsciiWolf** [comment]
Let's wait for the review from Adrien. If everything is ok, I will merge this PR. ;-)

**Pull request merged**
